#pragma once

enum class ERROR_CODE : unsigned short
{
	NONE = 0,

	USER_MGR_INVALID_USER_INDEX = 10,
	USER_MGR_INVALID_USER_UNIQUEID = 11,

	CREATE_ACCOUNT_FAIL = 20,

	LOGIN_USER_ALREADY = 30,
	LOGIN_USER_USED_ALL_OBJ = 31,
	LOGIN_USER_INVALID_PW = 32,

	NEW_ROOM_USED_ALL_OBJ = 40,
	NEW_ROOM_FAIL_ENTER = 41,

	ENTER_ROOM_NOT_FINDE_USER = 50,
	ENTER_ROOM_INVALID_USER_STATUS = 51,
	ENTER_ROOM_NOT_USED_STATUS = 52,
	ENTER_ROOM_FULL_USER = 53,

	ROOM_INVALID_INDEX = 60,
	ROOM_NOT_USED = 61,
	ROOM_TOO_MANY_PACKET = 62,
	ROOM_FULL = 63,

	LEAVE_ROOM_INVALID_ROOM_INDEX = 70,

	CHAT_ROOM_INVALID_ROOM_NUMBER = 80,
};
